import { PolicyPage, Section } from "@/components/PolicyPage";
import { CONTACT_EMAIL, OPERATOR_NAME, SITE_NAME } from "@/lib/site";

export const metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return (
    <PolicyPage title="Privacy Policy">
      <Section heading="1. Who we are">
        <p>
          {SITE_NAME} is operated by {OPERATOR_NAME}. This policy explains what
          personal data we collect, why, and the choices you have. Contact:{" "}
          {CONTACT_EMAIL}.
        </p>
      </Section>

      <Section heading="2. Data we collect">
        <p>
          <strong className="text-ink">Account data.</strong> Email address and
          authentication credentials (managed by Supabase Auth; passwords are
          hashed, and Google sign-in shares only your email and basic profile).
        </p>
        <p>
          <strong className="text-ink">Usage data.</strong> Searches you run,
          blueprints you view, save, or copy, validator runs, API requests, and
          Freedom-to-Operate orders. We use this to enforce plan limits, show
          you your usage, and improve the product.
        </p>
        <p>
          <strong className="text-ink">Content you submit.</strong> Ideas you
          paste into the Validator and patent numbers you submit for reports.
        </p>
        <p>
          <strong className="text-ink">Billing data.</strong> Handled by
          Stripe. We store your Stripe customer ID and subscription status —
          never card numbers.
        </p>
        <p>
          We do not run third-party advertising or cross-site tracking.
        </p>
      </Section>

      <Section heading="3. How we use AI providers">
        <p>
          To power the Validator, text you submit is converted to an embedding
          via a third-party AI provider (an OpenAI-compatible API). Blueprint
          and report text is generated by large language model providers.
          These providers process the text to provide the service; we configure
          providers not to use API traffic for model training where the
          provider offers that control. Do not paste confidential information
          you are not comfortable sending to a processor.
        </p>
      </Section>

      <Section heading="4. Subprocessors">
        <p>
          We use: Supabase (database, auth, file storage), Stripe (payments),
          Vercel (web hosting), Render (API hosting), and AI model providers
          for translation and embeddings. Each processes data only to provide
          their service to us.
        </p>
      </Section>

      <Section heading="5. Cookies">
        <p>
          We use essential cookies only: authentication/session cookies set by
          Supabase Auth so you stay signed in. No advertising or analytics
          cookies are set. Because we only use strictly necessary cookies, no
          cookie consent banner is required in most jurisdictions.
        </p>
      </Section>

      <Section heading="6. Retention">
        <p>
          Account and usage data are retained while your account is active.
          Validator idea text is processed to produce your results and stored
          transiently in service logs. Freedom-to-Operate PDFs are retained in
          private storage so you can re-download them. If you delete your
          account, we delete or de-identify your personal data within 30 days,
          except records we must keep for legal or accounting reasons (e.g.
          Stripe invoices).
        </p>
      </Section>

      <Section heading="7. Your rights">
        <p>
          Depending on your jurisdiction (including under GDPR and CCPA), you
          may have rights to access, correct, export, or delete your personal
          data, and to object to or restrict certain processing. Email{" "}
          {CONTACT_EMAIL} and we will respond within 30 days. We do not sell
          personal data.
        </p>
      </Section>

      <Section heading="8. Security">
        <p>
          Data is encrypted in transit (TLS) and at rest by our hosting
          providers. Row-level security restricts database access; API keys
          are stored as one-way hashes; report files live in private storage
          accessed via short-lived signed URLs. No system is perfectly secure —
          report concerns to {CONTACT_EMAIL}.
        </p>
      </Section>

      <Section heading="9. International transfers">
        <p>
          Our providers may process data in the United States and other
          countries. Where required, transfers rely on the providers&apos;
          standard contractual clauses or equivalent safeguards.
        </p>
      </Section>

      <Section heading="10. Children">
        <p>
          The service is not directed to children under 16, and we do not
          knowingly collect their data.
        </p>
      </Section>

      <Section heading="11. Changes">
        <p>
          We will announce material changes to this policy on the site or by
          email before they take effect.
        </p>
      </Section>
    </PolicyPage>
  );
}
